import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: "Create Next App",
    description: "Generated by create next app",
    other: {
      "fc:miniapp": JSON.stringify({
        version: "next",
        imageUrl: "https://your-app.com/embed-image",
        button: {
          title: `Launch Test App`,
          action: {
            type: "launch_miniapp",
            name: "Test App",
            url: "https://test-base-app.vercel.app",
            splashImageUrl: "https://test-base-app.vercel.app/globe.svg",
            splashBackgroundColor: "#000000",
          },
        },
      }),
    },
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
